from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from scripts.verify_dependency_lock import DependencyLockError, verify_lock


class DependencyLockTests(unittest.TestCase):
    @staticmethod
    def _write_lock(root: Path, *, package_line: str = "exampledb==1.5.9 \\") -> tuple[Path, Path]:
        requirements = root / "requirements.txt"
        requirements.write_text("exampledb==1.5.9\n", encoding="utf-8")
        lock = root / "requirements.lock"
        lock.write_text(
            "# This file is autogenerated by pip-compile with Python 3.11\n"
            "# by the following command:\n"
            "#    pip-compile --generate-hashes requirements.txt\n"
            "#\n"
            f"{package_line}\n"
            "    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
            "    # via -r requirements.txt\n",
            encoding="utf-8",
        )
        return requirements, lock

    def test_accepts_hashed_lock_with_matching_direct_pin(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            requirements, lock = self._write_lock(Path(directory))
            summary = verify_lock(requirements, lock)
        self.assertEqual(summary.direct_dependencies, 1)
        self.assertEqual(summary.locked_dependencies, 1)
        self.assertEqual(summary.hashes, 1)

    def test_rejects_version_drift(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            requirements, lock = self._write_lock(Path(directory), package_line="exampledb==1.5.8 \\")
            with self.assertRaisesRegex(DependencyLockError, "version drift"):
                verify_lock(requirements, lock)

    def test_rejects_requirement_without_hash(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            requirements, lock = self._write_lock(Path(directory))
            lock.write_text(
                "# This file is autogenerated by pip-compile\n"
                "# --generate-hashes\n"
                "exampledb==1.5.9\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(DependencyLockError, "lacks a hash"):
                verify_lock(requirements, lock)

    def test_accepts_uv_generated_lock(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            requirements, lock = self._write_lock(Path(directory))
            lock.write_text(
                "# This file was autogenerated by uv via the following command:\n"
                "#    uv pip compile --generate-hashes requirements.txt\n"
                "exampledb==1.5.9 \\\n"
                "    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
                encoding="utf-8",
            )
            summary = verify_lock(requirements, lock)
        self.assertEqual(summary.locked_dependencies, 1)


if __name__ == "__main__":
    unittest.main()
