"""Fail closed when the runtime hash lock no longer matches its direct inputs."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REQUIREMENTS = PROJECT_ROOT / "requirements.txt"
DEFAULT_LOCK = PROJECT_ROOT / f"requirements-py{sys.version_info.major}{sys.version_info.minor}.lock"
_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==([A-Za-z0-9][A-Za-z0-9_.+!-]*)$")
_LOCK_PIN = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==([A-Za-z0-9][A-Za-z0-9_.+!-]*)(?:\s*;[^\\]+)?\s*\\?$"
)
_HASH = re.compile(r"^\s+--hash=sha256:[0-9a-f]{64}\s*\\?$")
_NORMALIZE = re.compile(r"[-_.]+")


class DependencyLockError(ValueError):
    """The lock file is absent, malformed, or does not cover the direct inputs."""


@dataclass(frozen=True, slots=True)
class LockSummary:
    direct_dependencies: int
    locked_dependencies: int
    hashes: int


def _normalized_name(value: str) -> str:
    return _NORMALIZE.sub("-", value).lower()


def _read_lines(path: Path, description: str) -> list[str]:
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError) as error:
        raise DependencyLockError(f"{description} cannot be read") from error


def load_direct_pins(requirements_path: Path) -> dict[str, str]:
    """Read exact direct pins from the human-maintained runtime input."""

    pins: dict[str, str] = {}
    for raw in _read_lines(requirements_path, "runtime requirements"):
        value = raw.split("#", 1)[0].strip()
        if not value:
            continue
        match = _PIN.fullmatch(value)
        if match is None:
            raise DependencyLockError("runtime requirements must contain only exact direct pins")
        name = _normalized_name(match.group(1))
        if name in pins:
            raise DependencyLockError("runtime requirements contain duplicate package pins")
        pins[name] = match.group(2)
    if not pins:
        raise DependencyLockError("runtime requirements are empty")
    return pins


def load_locked_pins(lock_path: Path) -> tuple[dict[str, str], int]:
    """Read pip-compile hash entries without accepting unverified requirements."""

    lines = _read_lines(lock_path, "runtime lock")
    text = "\n".join(lines)
    if not (
        "# This file is autogenerated by pip-compile" in text
        or "# This file was autogenerated by uv" in text
    ):
        raise DependencyLockError("runtime lock was not generated by a supported compiler")
    if "--generate-hashes" not in text:
        raise DependencyLockError("runtime lock does not declare hash generation")

    pins: dict[str, str] = {}
    current_name: str | None = None
    current_hashes = 0
    hashes = 0

    def finish_current() -> None:
        nonlocal current_name, current_hashes
        if current_name is not None and current_hashes == 0:
            raise DependencyLockError(f"runtime lock entry lacks a hash: {current_name}")
        current_name = None
        current_hashes = 0

    for raw in lines:
        value = raw.rstrip()
        stripped = value.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if _HASH.fullmatch(value):
            if current_name is None:
                raise DependencyLockError("runtime lock has a hash without a requirement")
            current_hashes += 1
            hashes += 1
            continue
        if value.startswith("    # via"):
            continue
        if value.startswith("--"):
            finish_current()
            continue
        match = _LOCK_PIN.fullmatch(value)
        if match is None:
            raise DependencyLockError(f"runtime lock contains an unsupported requirement entry: {value!r}")
        finish_current()
        name = _normalized_name(match.group(1))
        if name in pins:
            raise DependencyLockError(f"runtime lock contains duplicate pin: {name}")
        pins[name] = match.group(2)
        current_name = name
    finish_current()
    if not pins:
        raise DependencyLockError("runtime lock is empty")
    return pins, hashes


def verify_lock(requirements_path: Path, lock_path: Path) -> LockSummary:
    """Require every direct pin to be present at the same version in a hashed lock."""

    direct_pins = load_direct_pins(requirements_path)
    locked_pins, hashes = load_locked_pins(lock_path)
    for name, version in direct_pins.items():
        locked_version = locked_pins.get(name)
        if locked_version is None:
            raise DependencyLockError(f"runtime lock is missing direct pin: {name}=={version}")
        if locked_version != version:
            raise DependencyLockError(
                f"runtime lock version drift: {name}=={locked_version}, expected {version}"
            )
    return LockSummary(
        direct_dependencies=len(direct_pins),
        locked_dependencies=len(locked_pins),
        hashes=hashes,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements", type=Path, default=DEFAULT_REQUIREMENTS)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    arguments = parser.parse_args(argv)
    try:
        summary = verify_lock(arguments.requirements, arguments.lock)
    except DependencyLockError as error:
        print(f"dependency lock rejected: {error}", file=sys.stderr)
        return 2
    print(
        "dependency lock verified: "
        f"{summary.direct_dependencies} direct, {summary.locked_dependencies} locked, "
        f"{summary.hashes} hashes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
